export const FETCH_LOGIN = 'FETCH_LOGIN';
export const SET_NEW_ROUTER = 'SET_NEW_ROUTER';
export const SET_AUTH = 'SET_AUTH';
export const SET_ROLE = 'SET_ROLE';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_BELONG_TO = 'SET_BELONG_TO';
export const SET_ROLE_NAME = 'SET_ROLE_NAME';
export const SET_LAST_LOGIN_IP = 'SET_LAST_LOGIN_IP';
// security
export const FETCH_SECURITY = 'FETCH_SECURITY';
export const SET_API_AGENTPAY_IS_LIMIT_IP = 'SET_API_AGENTPAY_IS_LIMIT_IP';
export const SET_API_AGENTPAY_LIMIT_IP = 'SET_API_AGENTPAY_LIMIT_IP';
export const SET_BACKEND_AGENTPAY_IS_LIMIT_IP = 'SET_BACKEND_AGENTPAY_IS_LIMIT_IP';
export const SET_BACKEND_AGENTPAY_LIMIT_IP = 'SET_BACKEND_AGENTPAY_LIMIT_IP';
export const SET_BACKEND_IS_LIMIT_IP = 'SET_BACKEND_IS_LIMIT_IP';
export const SET_BACKEND_LIMIT_IP = 'SET_BACKEND_LIMIT_IP';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_IS_GOOGLE_AUTHENTICATION = 'SET_IS_GOOGLE_AUTHENTICATION';
export const SET_IS_PAYPW = 'SET_IS_PAYPW';
export const SET_LAST_LOGIN_DATE = 'SET_LAST_LOGIN_DATE';
// global
export const FETCH_ACCOUNT_MAP = 'FETCH_ACCOUNT_MAP';
export const FETCH_PAYTYPE_MAP = 'FETCH_PAYTYPE_MAP';
export const FETCH_ROUTE_MAP = 'FETCH_ROUTE_MAP';
export const SET_ACCOUNT_MAP = 'SET_ACCOUNT_MAP';
export const SET_PAYTYPE_MAP = 'SET_PAYTYPE_MAP';
export const SET_PAYTYPE = 'SET_PAYTYPE';
export const SET_ROUTE_MAP = 'SET_ROUTE_MAP';
export const SET_ROUTE_EN_MAP = 'SET_ROUTE_EN_MAP';
export const SET_ROUTE = 'SET_ROUTE';
export const SET_BASE_URL = 'SET_BASE_URL';
// notifications
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATION_ONE = 'FETCH_NOTIFICATION_ONE';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_NOTIFICATION_IS_FETCHING = 'SET_NOTIFICATION_IS_FETCHING';
// clientInfo
export const FETCH_CLIENT_INFO = 'FETCH_CLIENT_INFO';
export const SET_AGENT_ACCOUNT = 'SET_AGENT_ACCOUNT';
export const SET_DETAIL = 'SET_DETAIL';
export const SET_TOTAL_BALANCE = 'SET_TOTAL_BALANCE';
export const SET_CLIENT_INFO_IS_FETCHING = 'SET_CLIENT_INFO_IS_FETCHING';
