apiVersion: v1
kind: Service
metadata:
  name: payment-client-vue-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8090
    nodePort: 30300
    protocol: TCP
    targetPort: 8080
  selector:
    app: payment-client-vue-dm