import './iview';
import Vue from 'vue';
import Row from 'iview/src/components/row';
import Col from 'iview/src/components/col';
import Layout from 'iview/src/components/layout';
import Header from 'iview/src/components/header';
import Content from 'iview/src/components/content';
import Menu from 'iview/src/components/menu';
import Button from 'iview/src/components/button';
import Card from 'iview/src/components/card';
import Table from 'iview/src/components/table';
import Panel from 'iview/src/components/panel';
import Collapse from 'iview/src/components/collapse';
import Input from 'iview/src/components/input';
import Modal from 'iview/src/components/modal';
import Breadcrumb from 'iview/src/components/breadcrumb';
import BreadcrumbItem from 'iview/src/components/breadcrumb-item';
import '../theme/iview-variables.less';

Vue.component('Row', Row);
Vue.component('Col', Col);
Vue.component('Layout', Layout);
Vue.component('Header', Header);
Vue.component('Content', Content);
Vue.component('Menu', Menu);
Vue.component('Submenu', Menu.Sub);
Vue.component('MenuItem', Menu.Item);
Vue.component('Button', Button);
Vue.component('Card', Card);
Vue.component('Table', Table);
Vue.component('Panel', Panel);
Vue.component('Collapse', Collapse);
Vue.component('Input', Input);
Vue.component('Modal', Modal);
Vue.component('Breadcrumb', Breadcrumb);
Vue.component('BreadcrumbItem', BreadcrumbItem);
